"""empty message

Revision ID: 782c006ee33e
Revises: 0e26f2babdf3
Create Date: 2026-05-05 19:14:40.831811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782c006ee33e'
down_revision: Union[str, Sequence[str], None] = '0e26f2babdf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_lead_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('amo_lead_id', sa.Integer(), nullable=False),
    sa.Column('lead_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amo_lead_links_amo_lead_id'), 'amo_lead_links', ['amo_lead_id'], unique=True)
    op.create_index(op.f('ix_amo_lead_links_telegram_chat_id'), 'amo_lead_links', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amo_lead_links_telegram_chat_id'), table_name='amo_lead_links')
    op.drop_index(op.f('ix_amo_lead_links_amo_lead_id'), table_name='amo_lead_links')
    op.drop_table('amo_lead_links')
    # ### end Alembic commands ###
