"""empty message

Revision ID: 7e1e6fd1739f
Revises: 782c006ee33e
Create Date: 2026-05-06 17:00:10.378438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e1e6fd1739f'
down_revision: Union[str, Sequence[str], None] = '782c006ee33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('ref_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_ref_code'), 'users', ['ref_code'], unique=True)
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_id', name='uq_referral_referred_id')
    )
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.drop_index(op.f('ix_amo_lead_links_amo_lead_id'), table_name='amo_lead_links')
    op.drop_index(op.f('ix_amo_lead_links_telegram_chat_id'), table_name='amo_lead_links')
    op.drop_table('amo_lead_links')
    op.add_column('certificates', sa.Column('plan_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'plan_name')
    op.create_table('amo_lead_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('telegram_chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('amo_lead_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lead_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('amo_lead_links_pkey'))
    )
    op.create_index(op.f('ix_amo_lead_links_telegram_chat_id'), 'amo_lead_links', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_amo_lead_links_amo_lead_id'), 'amo_lead_links', ['amo_lead_id'], unique=True)
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_users_ref_code'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
