"""empty message

Revision ID: fe62f39335a4
Revises: 5d7a3e6a0511
Create Date: 2026-05-13 19:14:21.465781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe62f39335a4'
down_revision: Union[str, Sequence[str], None] = '5d7a3e6a0511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('buyer_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'buyer_phone')
    # ### end Alembic commands ###
